# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'georef_auto_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeorefAutoDialog(object):
    def setupUi(self, GeorefAutoDialog):
        GeorefAutoDialog.setObjectName("GeorefAutoDialog")
        GeorefAutoDialog.resize(400, 300)
        self.formLayoutWidget = QtWidgets.QWidget(GeorefAutoDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 360, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.btnCarregarImagem = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnCarregarImagem.setObjectName("btnCarregarImagem")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.btnCarregarImagem)
        self.comboLayerReferencia = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboLayerReferencia.setObjectName("comboLayerReferencia")
        self.comboLayerReferencia.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.comboLayerReferencia)
        self.btnDesenharPoligono = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnDesenharPoligono.setObjectName("btnDesenharPoligono")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.btnDesenharPoligono)
        self.btnGeorreferenciar = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnGeorreferenciar.setObjectName("btnGeorreferenciar")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.btnGeorreferenciar)
        self.btnCancelar = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnCancelar.setObjectName("btnCancelar")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnCancelar)

        self.retranslateUi(GeorefAutoDialog)
        QtCore.QMetaObject.connectSlotsByName(GeorefAutoDialog)

    def retranslateUi(self, GeorefAutoDialog):
        _translate = QtCore.QCoreApplication.translate
        GeorefAutoDialog.setWindowTitle(_translate("GeorefAutoDialog", "Georreferenciamento automático"))
        self.btnCarregarImagem.setText(_translate("GeorefAutoDialog", "Carregar imagem"))
        self.comboLayerReferencia.setItemText(0, _translate("GeorefAutoDialog", "Selecionar imagem de referência"))
        self.btnDesenharPoligono.setText(_translate("GeorefAutoDialog", "Desenhar polígono"))
        self.btnGeorreferenciar.setText(_translate("GeorefAutoDialog", "Executar georreferenciamento"))
        self.btnCancelar.setText(_translate("GeorefAutoDialog", "Cancelar"))
