from typing import Protocol


class ProgressDialog(Protocol):
    def setPrimaryLabel(self, label: str): ...
    def setPrimaryTotal(self, total: int): ...
    def setPrimaryProgress(self, curr: int): ...
    def pushPrimaryProgress(self): ...
    def setSecondaryLabel(self, label: str): ...
    def setSecondaryTotal(self, total: int): ...
    def setSecondaryProgress(self, curr: int): ...
    def pushSecondaryProgress(self): ...
    def setTertiaryLabel(self, label: str): ...
    def setTertiaryTotal(self, total: int): ...
    def setTertiaryProgress(self, curr: int): ...
    def pushTertiaryProgress(self): ...
    def show(self): ...
    def wasCanceled(self) -> bool: ... 
